### ISSUE TITLE
Build system is not automated

### ISSUE THREAD

**Issue by insanity54** [insanity54/futureporn#126]
There isn't a single thing that is automated right now. Everything is broken.

I have to manually do **everything**.

PLEASE IMPLEMENT #106 

Priority number 1 is the BUILDER
Not scout.
Not capture.
Not commander.

BUILDER.

EDIT: let's note some intermediate steps to achieve a state of no broken-ness

## main workflow

* [x] Builder reliably builds the site
* [ ] Builder reliably git pushes the build artifacts
* [ ] Builder reacts to `capture/vod/upload` notification, building and uploading
* [ ] Builder deployment playbook copies the local cache to the cloud
* [ ] Builder deployed to cloud
* [x] Commander has a `scout/stream/stop` button (temporary, until scout emits this automatically)
* [ ] Capture instances respond to `scout/stream/stop` notification, responding with their own manifest
* [ ] Commander elects a capture instance
* [ ] Capture instance combines vod segments
* [ ] Capture instance uploads vod
* [ ] Capture instance saves CID to db
* [ ] Capture instance notifies `capture/vod/upload`
* [ ] Builder reacts to `capture/vod/upload` notification
* [ ] Builder reacts to `render/transcode/upload` notification, building the site

## optimization workflow

* [x] Futureporn/Render randomly chooses a VOD without video240Hash
* [x] Render downloads that videoSrcHash
* [x] Render transcodes the source VOD to 240p
* [x] Render creates a thiccHash
* [ ] Render saves video240Hash and thiccHash to the db
* [ ] Render notifies on `render/upload`
* [ ] Render deployment playbook
* [x] Render deployed to cloud

**Comment by insanity54** [comment]
24 hours spent awake due to yarn 3, webpack, eleventy incompatibilities all because I wanted to use monorepo workspaces.

 #106 

I'm regretting not doing the easy thing, which would have been importing packages/common/logger from packages/scout/index using a relative path.

Instead I did the hard thing, setting up yarn workspaces which required upgrading to yarn3 with all it's breaking changes.

ended up not being able to solve the problem. I can build locally, but not on the build server. I can't reproduce the build server's failure locally. I just want to sleep. 

#106

**Comment by Linden10** [comment]
GANBATTE!! This is a passionate projekt (heh) and I believe you can handle it!
Wish I knew some of the coding needed so I can contribute...oh well, don't overstress and good luck!

Also the reasoning I'm commenting is that, with ProjektMelody's 3rd Anniversary Stream yesterday, I recorded it with the
[ctbrec program](https://mastodon.cloud/@ctbrec) and noticed that the first half of the stream was in 720p 30fps while the 2nd half (where she starts reacting to her community's videos) is in 1080p 60fps!

So knowing that your archive of the stream is in 720p incl. the second half, I thought I'll share the 2nd half of the stream I have that's in 1080p 60fps if you don't have it. You can choose to create a secondary link, keep a copy or whatever.
Hope you don't mind! ^^
https://mega.nz/file/RNZT3ZrQ#2qkkYk7ZgtNHcB1pL1W4TVi68BQHzV5SxlSLXPWaSLM

I'll be delete this mega link after you got it.

**Comment by insanity54** [comment]
Oh I didn't even realize that the second half was 1080p@60! I know Mel restarted stream to switch rooms at one point but I didn't think to check a resolution difference. This is very appreciated, thank you! 

I just checked and it looks like I did record the second half at 1080p@60 but then I concatenated that recording with the first half which was at 720p@30. Whoops! IDK if that will even play correctly. 

Anyway I think what I'll do is I'll make two separate vod entries for this stream. That way they each have their original resolution. I'm downloading your recording now. It's a little bigger filesize than what I got so I'm going to compare. My internet is really slow so it'll probably take a day. I'll let you know when it's finished.

Yeah it's a passion project for sure. Thanks for your kind words, they mean a lot. I'm gonna get through it one day at a time. I get high on stress sometimes :exploding_head: but yeah, you give good advice :smile: . Made some good progress yesterday on getting things running smoothly again. I'm constantly learning how to make things better, more robust.

Also thanks for the ctbrec program info. I hadn't heard of that before and I'm going to look into it some more.

**Comment by insanity54** [comment]
Thanks @Linden10, I got the vod downloaded

**Comment by Linden10** [comment]
Your welcome! I'll keep the mega link up a bit longer incase something happens...yup!

**Comment by insanity54** [comment]
Superseded by #166
